title: "Mostafa Hirch | Cybersecurity Professional"
description: "Portfolio of Mostafa Hirch, an aspiring Cybersecurity Analyst focusing on network infrastructure and security controls."
theme: jekyll-theme-architect
baseurl: "/MHdae6monthCohort"
show_downloads: false 